/*
 * This file is generated by jOOQ.
*/
package com.airbnb.banana.db;


import com.airbnb.banana.db.tables.Bananatypes;
import com.airbnb.banana.db.tables.Transactions;
import com.airbnb.banana.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1262696640;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>BananaTypes</code>.
     */
    public final Bananatypes BANANATYPES = com.airbnb.banana.db.tables.Bananatypes.BANANATYPES;

    /**
     * The table <code>Transactions</code>.
     */
    public final Transactions TRANSACTIONS = com.airbnb.banana.db.tables.Transactions.TRANSACTIONS;

    /**
     * The table <code>Users</code>.
     */
    public final Users USERS = com.airbnb.banana.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Bananatypes.BANANATYPES,
            Transactions.TRANSACTIONS,
            Users.USERS);
    }
}
