/*
 * This file is generated by jOOQ.
*/
package com.airbnb.banana.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transactions implements Serializable {

    private static final long serialVersionUID = -1083657841;

    private Integer id;
    private Integer sender;
    private Integer receiver;
    private Integer amount;

    public Transactions() {}

    public Transactions(Transactions value) {
        this.id = value.id;
        this.sender = value.sender;
        this.receiver = value.receiver;
        this.amount = value.amount;
    }

    public Transactions(
        Integer id,
        Integer sender,
        Integer receiver,
        Integer amount
    ) {
        this.id = id;
        this.sender = sender;
        this.receiver = receiver;
        this.amount = amount;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSender() {
        return this.sender;
    }

    public void setSender(Integer sender) {
        this.sender = sender;
    }

    public Integer getReceiver() {
        return this.receiver;
    }

    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    public Integer getAmount() {
        return this.amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transactions (");

        sb.append(id);
        sb.append(", ").append(sender);
        sb.append(", ").append(receiver);
        sb.append(", ").append(amount);

        sb.append(")");
        return sb.toString();
    }
}
