version: '3'


services:
  prometheus-push-gateway:
    image: prom/pushgateway:v0.5.0
    ports:
      - "9091:9091"
  prometheus:
    image: ziliang/prometheus
    volumes:
      - /data/ig-prometheus:/prometheus
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  grafana:
    image: grafana/grafana:5.1.3
    volumes:
      - /data/ig-grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
