version: '3'
services:
  reckless:
    # docker-compose up -d reckless
    image: ziliang/reckless
    build: .
    container_name: reckless
    ports:
      - "80:80"
    volumes:
      - /data/reckless:/reckless/static/data
    environment:
      - DD_HOST
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - d
networks:
  d:
