version: '3.3'

services:
  ardb-2:
  # user https://github.com/yaauie/redis-copy/ to dump redis from old redis to here
    image: ziliang/ardb
#    ports:
#      - "6379:16379"
    volumes:
      - /data/ig-ardb-2:/var/lib/ardb
    deploy:
      placement:
        constraints:
          - node.role == manager

  ardb-cache-2:
    image: ziliang/ardb
    deploy:
      mode: global
#    ports:
#      - "16379:16379"
#  prometheus-push-gateway:
#    image: prom/pushgateway:v0.5.0
#    ports:
#      - "9091:9091"
#  prometheus:
#    build:
#      context: .
#      dockerfile: prom.Dockerfile
#    volumes:
#      - /data/ig-prometheus:/prometheus
#    links:
#     - prometheus-push-gateway:prometheus-push-gateway
#    ports:
#      - "9090:9090"
#  influxdb:
#    image: influxdb:1.5.3
#    volumes:
#      - /data/ig-influx:/var/lib/influxdb
#    ports:
#      - "8086:8086"  #  HTTP API
#      - "8083:8083"  #  Admin interface
#  grafana:
#    image: grafana/grafana:5.1.3
#    volumes:
#      - /data/ig-grafana:/var/lib/grafana
#    links:
#     - prometheus:prometheus
#    ports:
#      - "3000:3000"
#  goproxy:
#    build:
#      context: .
#      dockerfile: go.Dockerfile
#    container_name: goproxy
#    entrypoint:
#      - "./main"
#      - "-t"
#      - "proxy"
  z-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "z"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  v-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "v"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  hix-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "hix"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  newdone-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "newdone"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  mc-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "mc"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  eaxy-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "eaxy"
    configs:
      - source: user_config
        target: /instagram/user_config.local
  eva-bot:
    image: ziliang/igbot
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "eva"
    configs:
      - source: user_config
        target: /instagram/user_config.local
#  airbnb-bot:
#    image: ziliang/igbot
#    volumes:
#      - /data/ig:/data/ig
#    environment:
#      - DD_HOST
#      - PROM_HOST
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "airbnb"
#    configs:
#      - source: user_config
#        target: /instagram/user_config.local
#  v-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "v"
#  mc-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "mc"
#  hix-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "hix"
#  newdone-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "newdone"
#  let-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "let"
#  eva-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "eva"
#  eaxy-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "eaxy"
#  b1-bot:
#    extends:
#      service: basebot
#    entrypoint:
#      - "python"
#      - "bot.py"
#      - "-u"
#      - "b1"

#  likes:
#    build:
#      context: .
#      dockerfile: go.Dockerfile
#    container_name: ig-likes
#    entrypoint:
#      - "/app/main"
#      - "-t"
#      - "likes"
#      - "-u"
#  follow:
#    build:
#      context: .
#      dockerfile: go.Dockerfile
#    container_name: ig-follow
#    entrypoint:
#      - "/app/main"
#      - "-t"
#      - "follow"
#      - "-u"
#  post:
#    build: .
#    container_name: ig-post
#    volumes:
#      - /data/ig:/data/ig
#    environment:
#      - DD_HOST
#      - PROM_HOST
#    entrypoint:
#      - "python"
#      - "post.py"
#      - "-u"
#    links:
#     - ardb-2:redis
#     - ardb-cache-2:redis-cache-2

configs:
  user_config:
    file: ./user_config.local

#We need a way to achieve the following:
#- one click to bring up all of the several accounts on prod
#- one click to bring up another account on dev
#
#Existing tools:
#- runit service
#  - auto start after reboot
#  - can monitor status of each
#  - make sure always up, and exactly one instance
#- docker-compose run
#  - parameterizable of service definition
#  - need to manually run (cannot survive reboot)
#  - will have N instance if run N times
#- docker-compose up
#  - not parameteriable
#  - exactly one instance
#  - need manually run (cannot survive reboot)
#
#Solution:
#- runit + compose run
#  - one docker-compose service, several runit service
#- docker-compose up
#  - need to run individually for each account, unless prod and dev have different difinition file
