version: '2'

# TODO: compose supports 'extends', so we can abstract common bot logic into gneral-bot service
# TODO: compose supports `-f` to load different config files. Can implement some one-off jobs in another file
# TODO: maybe can use environment variable (either Dockerfile level or compose level) to customize one bot service
services:
  ardb-2:
  # user https://github.com/yaauie/redis-copy/ to dump redis from old redis to here
    build:
      context: ../docker
      dockerfile: ardb.Dockerfile
      args:
        engine: leveldb
    container_name: ardb-server-2
    ports:
      - "6379:16379"
    volumes:
      - /data/ig-ardb-2:/var/lib/ardb
  ardb-cache-2:
    build:
      context: ../docker
      dockerfile: ardb.Dockerfile
      args:
        engine: leveldb
    container_name: ardb-server-cache-2
    ports:
      - "26379:16379"
  redis-cache:
    image: redis:2.8
    container_name: redis-cache
  prometheus-push-gateway:
    image: prom/pushgateway:v0.5.0
    ports:
      - "9091:9091"
  prometheus:
    build:
      context: .
      dockerfile: prom.Dockerfile
    volumes:
      - /data/ig-prometheus:/prometheus
    links:
     - prometheus-push-gateway:prometheus-push-gateway
    ports:
      - "9090:9090"
  influxdb:
    image: influxdb:1.5.3
    volumes:
      - /data/ig-influx:/var/lib/influxdb
    ports:
      - "8086:8086"  #  HTTP API
      - "8083:8083"  #  Admin interface
  grafana:
    image: grafana/grafana:5.1.3
    volumes:
      - /data/ig-grafana:/var/lib/grafana
    links:
     - prometheus:prometheus
    ports:
      - "3000:3000"
  goproxy:
    build:
      context: .
      dockerfile: go.Dockerfile
    container_name: goproxy
    entrypoint:
      - "./main"
      - "-t"
      - "proxy"
  basebot:
    build: .  # TODO: if we publish this image in CI, we can pull from registry
    volumes:
      - /data/ig:/data/ig
      - ./user_config.local:/instagram/user_config.local
    environment:
      - DD_HOST
      - PROM_HOST
  auth:
    extends:
      service: basebot
    entrypoint:
      - "bash"
  z-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "z"
  airbnb-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "airbnb"
  v-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "v"
  mc-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "mc"
  hix-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "hix"
  newdone-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "newdone"
  let-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "let"
  eva-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "eva"
  eaxy-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "eaxy"
  b1-bot:
    extends:
      service: basebot
    entrypoint:
      - "python"
      - "bot.py"
      - "-u"
      - "b1"
  likes:
    build:
      context: .
      dockerfile: go.Dockerfile
    container_name: ig-likes
    entrypoint:
      - "/app/main"
      - "-t"
      - "likes"
      - "-u"
  follow:
    build:
      context: .
      dockerfile: go.Dockerfile
    container_name: ig-follow
    entrypoint:
      - "/app/main"
      - "-t"
      - "follow"
      - "-u"
  post:
    build: .
    container_name: ig-post
    volumes:
      - /data/ig:/data/ig
    environment:
      - DD_HOST
      - PROM_HOST
    entrypoint:
      - "python"
      - "post.py"
      - "-u"
    links:
     - ardb-2:redis
     - ardb-cache-2:redis-cache-2

#We need a way to achieve the following:
#- one click to bring up all of the several accounts on prod
#- one click to bring up another account on dev
#
#Existing tools:
#- runit service
#  - auto start after reboot
#  - can monitor status of each
#  - make sure always up, and exactly one instance
#- docker-compose run
#  - parameterizable of service definition
#  - need to manually run (cannot survive reboot)
#  - will have N instance if run N times
#- docker-compose up
#  - not parameteriable
#  - exactly one instance
#  - need manually run (cannot survive reboot)
#
#Solution:
#- runit + compose run
#  - one docker-compose service, several runit service
#- docker-compose up
#  - need to run individually for each account, unless prod and dev have different difinition file
