version: '3'
services:
  ardb:
    # docker-compose up -d ardb
    image: lupino/ardb-server
    container_name: ardb-server
    ports:
      - "6379:16379"
    volumes:
      - /data/ig-ardb:/var/lib/ardb
  bot:
    build: .
    volumes:
      - /data/instagram:/data/instagram
    # links is deprecated. we want to migrate to docker's user defined network.
    # we may also provision ardb inside here (bot own its data storage)
    links:
     - ardb:redis
