version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "81:81"
    links:
     - reckless:reckless
    networks:
      - d
  reckless:
    # docker-compose up -d reckless
    image: ziliang/reckless
    build: ../reckless
    container_name: reckless
    ports:
      - "8080:80"
    volumes:
      - /data/reckless:/reckless/static/data
    environment:
      - DD_HOST
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - d
networks:
  d:
