java_binary(
    name = "JooqPrototype",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = ['jooq-3.9.5.jar', 'mysql-connector-java-5.1.44/mysql-connector-java-5.1.44-bin.jar'],
    main_class = "io.naoshima.Main",
)
