#!/bin/bash

function compress {
    crf=$1
    input_file=$2
    res=`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 $input_file`
    w=`echo $res | cut -f 1 -d 'x'`
    h=`echo $res | cut -f 2 -d 'x'`
    echo "Width: $w"
    echo "Height: $h"
    echo "CRF: $crf"

    outfile="$input_file-converted-h265br-hvc1-crf-$crf.mp4"
    tmpfile="$outfile.tmp.mp4"

  if [ -f "$outfile" ]; then
    echo "skipping..."
  else
    echo "working..."
    # need a ARM-built ffmpeg with hevc_videotoolbox
    ffmpeg -i $input_file -map_metadata 0 -movflags use_metadata_tags -c:v hevc_videotoolbox -q:v "$crf" -tag:v hvc1 "$tmpfile"
    if [ $? -ne 0 ]; then
      echo "is interrupted."
      return 1
    else
      mv "$tmpfile" "$outfile"
      mdate.py "$outfile"
      # br-fname.py "$outfile"
    fi
  fi

}

crf=$1
shift

for fname in "$@"
do
    compress $crf $fname
done
