#!/bin/bash

function compress {
    scale=$1
    input_file=$2
    res=`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 $input_file`
    w=`echo $res | cut -f 1 -d 'x'`
    h=`echo $res | cut -f 2 -d 'x'`
    echo "Width: $w"
    echo "Height: $h"
    bitrate=$((w*h*scale))
    echo "Bitrate: $bitrate"

    outfile="$input_file-converted-hvc1-br-$bitrate.mp4"
    tmpfile="$outfile.tmp.mp4"

  if [ -f "$outfile" ]; then
    echo "skipping..."
  else
    echo "working..."
    ffmpeg -i $input_file -map_metadata 0 -movflags use_metadata_tags -c:v hevc_videotoolbox -tag:v hvc1 -b:v "$bitrate" "$tmpfile"
    if [ $? -ne 0 ]; then
      echo "is interrupted."
      return 1
    else
      mv "$tmpfile" "$outfile"
      mdate.py "$outfile"
    fi
  fi

}

n=$1
shift

for fname in "$@"
do
    compress $n $fname
done
